// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQUcvDFtOQZNKLK_LA66luLilygdeBHfo',
    appId: '1:37523367691:web:4d8a12751042611ddea40e',
    messagingSenderId: '37523367691',
    projectId: 'toologchbuka2008',
    authDomain: 'toologchbuka2008.firebaseapp.com',
    storageBucket: 'toologchbuka2008.firebasestorage.app',
    measurementId: 'G-Q5NMN9MSR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG_MJvfldgoKEBo7XVvwO7dg5d-A62Dyg',
    appId: '1:37523367691:android:034245d7a2a2fadedea40e',
    messagingSenderId: '37523367691',
    projectId: 'toologchbuka2008',
    storageBucket: 'toologchbuka2008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmsSa3a5_mrpEeFIh-tJa3qm_XH8Ti98',
    appId: '1:37523367691:ios:cdb196abb789d441dea40e',
    messagingSenderId: '37523367691',
    projectId: 'toologchbuka2008',
    storageBucket: 'toologchbuka2008.firebasestorage.app',
    iosBundleId: 'com.example.inventoryCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSmsSa3a5_mrpEeFIh-tJa3qm_XH8Ti98',
    appId: '1:37523367691:ios:cdb196abb789d441dea40e',
    messagingSenderId: '37523367691',
    projectId: 'toologchbuka2008',
    storageBucket: 'toologchbuka2008.firebasestorage.app',
    iosBundleId: 'com.example.inventoryCloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQUcvDFtOQZNKLK_LA66luLilygdeBHfo',
    appId: '1:37523367691:web:b518dd93220dd290dea40e',
    messagingSenderId: '37523367691',
    projectId: 'toologchbuka2008',
    authDomain: 'toologchbuka2008.firebaseapp.com',
    storageBucket: 'toologchbuka2008.firebasestorage.app',
    measurementId: 'G-SSCNE6EM4X',
  );
}
